fastlane_version '2.53.1'

#before_all do
#  ensure_git_branch(branch: 'main')
#  ensure_git_status_clean
#end


platform :ios do
   # iOS Lanes
end

platform :android do
  desc 'Build the Android application.'
  lane :dev do
      gradle(task: 'clean', project_dir: 'android/')
      gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
    end

  lane :alpha do
    #increment_version_code(gradle_file_path: 'android/app/build.gradle')
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
    upload_to_play_store_internal_app_sharing(json_key: '/Users/derkweijers/Nextcloud/Certs/Playstore/fastlane_deploy_key.json', apk: 'android/app/build/outputs/apk/release/app-release.apk')
  end
end
