fastlane_version '2.53.1'

platform :android do
   desc 'Build the Android application for internal testing'
   lane :internal do
     ensure_git_branch(branch: 'development')
     increment_version_code(gradle_file_path: 'android/app/build.gradle')
     gradle(task: 'clean', project_dir: 'android/')
     gradle(task: 'bundle', build_type: 'Release', project_dir: 'android/')
     upload_to_play_store(package_name: 'xyz.weijers.launchtoday', json_key: '/Users/derkweijers/Nextcloud/Certs/Playstore/fastlane_deploy_key.json', apk: 'android/app/build/outputs/bundle/release/app-release.aab', track: 'internal')
     git_commit(path: "./android/app/build.gradle", message: "Version Bump")
     push_to_git_remote()
   end

  # Normally we'll promote through the store, but this is here just in case
  desc 'Build the Android application for alpha testing'
  lane :alpha do
    # This should happen when building the internal version
    # increment_version_code(gradle_file_path: 'android/app/build.gradle')
    # gradle(task: 'clean', project_dir: 'android/')
    # gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
    upload_to_play_store(package_name: 'xyz.weijers.launchtoday', json_key: '/Users/derkweijers/Nextcloud/Certs/Playstore/fastlane_deploy_key.json', apk: 'android/app/build/outputs/bundle/release/app-release.aab', track: 'alpha')
  end
end
