fastlane_version '2.53.1'

#before_all do
  ensure_git_branch(branch: 'main')
  # Don't need this now
  # ensure_git_status_clean
#end


platform :ios do
   # iOS Lanes
end

platform :android do
  desc 'Build the Android application for local use.'
  lane :dev do
      gradle(task: 'clean', project_dir: 'android/')
      gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
    end

   desc 'Build the Android application for internal testing'
   lane :internal do
     increment_version_code(gradle_file_path: 'android/app/build.gradle')
     gradle(task: 'clean', project_dir: 'android/')
     gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
     upload_to_play_store(package_name: 'xyz.weijers.launchtoday', json_key: '/Users/derkweijers/Nextcloud/Certs/Playstore/fastlane_deploy_key.json', apk: 'android/app/build/outputs/apk/release/app-release.apk', track: 'internal')
     git_commit(path: "./android/app/build.gradle", message: "Version Bump")
     push_to_git_remote()
   end

  # Normally I'll promote through the store, but this is here just in case
  desc 'Build the Android application for alpha testing'
  lane :alpha do
    # This should happen when building the internal version
    # increment_version_code(gradle_file_path: 'android/app/build.gradle')
    # gradle(task: 'clean', project_dir: 'android/')
    # gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
    upload_to_play_store(package_name: 'xyz.weijers.launchtoday', json_key: '/Users/derkweijers/Nextcloud/Certs/Playstore/fastlane_deploy_key.json', apk: 'android/app/build/outputs/apk/release/app-release.apk', track: 'alpha')
  end
end
